### ISSUE TITLE
Enhance _errorIfUnmatchedBrackets to check for proper nesting

### ISSUE THREAD

**Issue by rfk** [mozilla/grunt-l10n-lint#2]
IIUC, the `_errorIfUnmatchedBrackets` function currently just checks that there's the same number of `>` as there are `<` in the string.  We could enhance this to check for proper nesting, so that things like `> <` are rejected.

**Comment by shane-tomlinson** [comment]
>  We could enhance this to check for proper nesting, so that things like > < are rejected.

That _should_ already be rejected since a tag won't be open before one is being closed. If a test for that doesn't exist, we should have one.

**Comment by shane-tomlinson** [comment]
The other catch for this case is the [unclosed tag check](https://github.com/mozilla/grunt-l10n-lint/blob/master/lib/check-translation.js#L185-L189). If neither of these checks work as expected, I think this should be taken care of in [errorIfMismatchedOpenAndCloseTags](https://github.com/mozilla/grunt-l10n-lint/blob/master/lib/check-translation.js#L174-L183).

**Comment by shane-tomlinson** [comment]
Created a test. Wah wah. I fail. :D Thanks @rfk!
